spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://127.0.0.1:5432/ip_rules_db"
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: "public"
        jdbc:
          batch_size: 100
    show-sql: false
  jackson:
    default-property-inclusion: NON_NULL